---
  name: Joblock
  name:zh-CN: 求职助手（按条件屏蔽公司）
  namespace: http://tampermonkey.net/
  version: 0.2002.22.0
  description: 1. 快捷添加企业黑名单； 2. 年薪显示 3. 依据年薪过滤工作 4. 目前支持Boss直聘、拉勾网
  author: 203X
  include:
    - http://localhost:3300/
  match:
    - '*://www.zhipin.com/*'
    - '*://www.lagou.com/*'
    - '*://www.liepin.com/*'
  grant:
    - GM_getValue
    - GM_setValue
    - GM_addStyle
    - GM_log
    # - GM_registerMenuCommand
    # - GM_listValues
  run-at: document-end
